language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls --use-mirrors && export HAS_COVERALLS=1; fi

script: python setup.py test

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
